### ISSUE TITLE
Factuurtotalen

### ISSUE THREAD

**Issue by thijsmie** [davidv1992/madmin#30]
Factuurtotalen moeten met aantal*stukprijs worden berekend, niet met totaalprijs.

**Comment by mrngm** [comment]
Want afrondingen?

**Comment by kashout** [comment]
hoi, om nog wat afrondingsfouten te vermijden zou ook Borrelmargetotaal anders berekend moeten worden. Ik heb met Matlab wat geprobeerd (i know, such programming) en kwam bij het volgende. Bij het weergeven van Borrelmargetotaal moet eerst per product de oude stukprijs worden berekend (voor optellen van borrelmarge), waarna borrelmarge bepaald kan worden door som over stukprijs*aantal voor alle regels. Dat kan door te delen door 1.03 en naar boven af te ronden (er vanuit gaande dat als ik het goed begrijp   totaalprijs = int(totaalprijs \* (1 + product['borrelmarge'] / 10000.))  effectief naar beneden afrond). 
Matlab test code:
x=10000000;

A = [1:x];
for i = 1:x
    A(2,i) = floor(A(1,i)*1.03);
end
for j = 1:x
    A(3,j) = ceil(A(2,j)/1.03);
end
y = 0;
z = 0;
for k = 1:x
    if A(3,k) == A(1,k)
        y = y+1;
    else 
        z = z+1;
    end
end

met z returned altijd 0 en y returned x
